version: '3'

tasks:
  get: npm install
  clean: rm -rf .parcel-cache dist
  web:watch: npx -y parcel index.html
  web:serve: 
   - task: clean
   - npx -y parcel serve index.html
  logger:serve: python3 obs_keylogger.py
  tmux: > 
    tmux new-session 'mosquitto' \; 
    split-window -h 'MQTT_HOST=127.0.0.1 && task web:watch' \;
    split-window -h 'MQTT_HOST=127.0.0.1 && task logger:serve' \;
    select-pane -t 0 \;
